#ifndef STM32WB55XX_DMA_H
#define STM32WB55XX_DMA_H

#include <stdint.h>
#include <stdbool.h>
#include <mcu/interfaces/dma.h>

typedef enum dma_data_size {
    DMA_TRANSFER_SIZE_8BITS,
    DMA_TRANSFER_SIZE_16BITS,
    DMA_TRANSFER_SIZE_32BITS,
} dma_data_size_t;

typedef enum dma_request_id {
    DMA_REQUEST_ID_MEMORY_TO_MEMORY,
    DMA_REQUEST_ID_GEN0,
    DMA_REQUEST_ID_GEN1,
    DMA_REQUEST_ID_GEN2,
    DMA_REQUEST_ID_GEN3,
    DMA_REQUEST_ID_ADC1,
    DMA_REQUEST_ID_SPI1_RX,
    DMA_REQUEST_ID_SPI1_TX,
    DMA_REQUEST_ID_SPI2_RX,
    DMA_REQUEST_ID_SPI2_TX,
    DMA_REQUEST_ID_I2C1_RX,
    DMA_REQUEST_ID_I2C1_TX,
    DMA_REQUEST_ID_I2C3_RX,
    DMA_REQUEST_ID_I2C3_TX,
    DMA_REQUEST_ID_USART1_RX,
    DMA_REQUEST_ID_USART1_TX,
    DMA_REQUEST_ID_LPUART1_RX,
    DMA_REQUEST_ID_LPUART1_TX,
    DMA_REQUEST_ID_SAI1_A,
    DMA_REQUEST_ID_SAI1_B,
    DMA_REQUEST_ID_QUADSPI,
    DMA_REQUEST_ID_TIM1_CH1,
    DMA_REQUEST_ID_TIM1_CH2,
    DMA_REQUEST_ID_TIM1_CH3,
    DMA_REQUEST_ID_TIM1_CH4,
    DMA_REQUEST_ID_TIM1_UP,
    DMA_REQUEST_ID_TIM1_TRIG,
    DMA_REQUEST_ID_TIM1_COM,
    DMA_REQUEST_ID_TIM2_CH1,
    DMA_REQUEST_ID_TIM2_CH2,
    DMA_REQUEST_ID_TIM2_CH3,
    DMA_REQUEST_ID_TIM2_CH4,
    DMA_REQUEST_ID_TIM2_UP,
    DMA_REQUEST_ID_TIM16_CH1,
    DMA_REQUEST_ID_TIM16_UP,
    DMA_REQUEST_ID_TIM17_CH1,
    DMA_REQUEST_ID_TIM17_UP,
    DMA_REQUEST_ID_AES1_IN,
    DMA_REQUEST_ID_AES1_OUT,
    DMA_REQUEST_ID_AES2_IN,
    DMA_REQUEST_ID_AES2_OUT
} dma_request_id_t;

typedef enum dma_interrupt_status {
    DMA_INTERRUPT_STATUS_GLOBAL_INTERRUPT = 1,
    DMA_INTERRUPT_STATUS_TRANSFER_COMPLETE = 2,
    DMA_INTERRUPT_STATUS_HALF_TRANSFER = 4,
    DMA_INTERRUPT_STATUS_TRANSFER_ERROR = 8
} dma_interrupt_status_t;

typedef struct mcu_dma_configuration {
    dma_request_id_t request_id;;
} mcu_dma_configuration_t;

#endif
